---
- name: "Create consul user"
  user:
    name: consul
    comment: "Conul User"
    group: consul
- name: "download consul"
  get_url: 
    url: "{{consul_download_url}}"
    dest: /tmp/consul.zip
- name: Extract consul
  become: true
  unarchive:
    src: /tmp/consul.zip
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    remote_src: yes
- name: Creates consul config directory
  become: true
  file: path=/etc/consul.d/ state=directory
- name: Configure consul
  become: true
  template:
    src: "files/config.j2"
    dest: /etc/consul.d/config.json
    mode: 0644
- name: Configure consul gossip encryption
  become: true
  template:
    src: "files/encrypt.j2"
    dest: /etc/consul.d/encrypt.json
    mode: 0644
- name: Systemd configuration
  become: true
  copy:
    src: "files/consul.service"
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644