---
- name: Start consul
  become: true
  systemd:
    name: consul
    state: started
    daemon_reload: yes
    enabled: yes
- name: Restart consul
  become: true
  systemd:
    name: consul
    state: restarted
    daemon_reload: yes
    enabled: yes
- name: Stop consul
  become: true
  systemd:
    name: consul
    state: stopped 
    daemon_reload: yes
    enabled: yes